---
- name: Restart kiosk
  ansible.builtin.systemd:
    name: kiosk
    state: restarted
    daemon_reload: true

- name: Run ldconfig
  ansible.builtin.command: ldconfig
  changed_when: true

- name: Restart rgb-server
  ansible.builtin.systemd:
    name: rgb-server
    state: restarted
    daemon_reload: true

- name: Reboot
  ansible.builtin.reboot:
