all:
  children:
    charge_kiosks:
      hosts:
        charge-alerts1:
          ansible_ssh_private_key_file: ~/.ssh/charge-alerts
        charge-alerts2:
          ansible_ssh_private_key_file: ~/.ssh/charge-alerts
        charge-alerts3:
          ansible_ssh_private_key_file: ~/.ssh/charge-alerts
        charge-alerts4:
          ansible_ssh_private_key_file: ~/.ssh/charge-alerts
    meetup_kiosks:
      hosts:
        meetup-alerts:
          ansible_host: meetup-alerts.local
          ansible_ssh_private_key_file: ~/.ssh/meetup-alerts
